name: Dockerfile CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'dockerfiles/**'
      - '.github/workflows/dockerfiles_ci.yml'

jobs:
  dockerfile-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine changed paths
        id: changed-paths
        run: |
          # Get the list of changed paths
          changed_paths=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^dockerfiles/|\.github/workflows/dockerfiles_ci\.yml$' || true)
          echo "Changed paths: $changed_paths"
          echo "::set-output name=changed-paths::$changed_paths"

      - name: Build Docker image
        run: |
          # Split the changed paths into an array
          IFS=$'\n' read -r -a paths_array <<< "${{ steps.changed-paths.outputs.changed-paths }}"

          # Build all Dockerfile directories if workflow file is changed
          for path in "${paths_array[@]}"; do
            if [[ $path == '.github/workflows/dockerfiles_ci.yml' ]]; then
              for folder in dockerfiles/*; do
                if [ -d "$folder" ]; then
                  echo "Building $folder ..."
                  folder_name=$(basename "$folder")
                  docker build -t "$folder_name" "$folder"
                fi
              done
              exit 0
            fi
          done

          # Build only changed Dockerfile directories
          for folder in "${paths_array[@]}"; do
            if [ -d "$folder" ]; then
              echo "Building $folder ..."
              folder_name=$(basename "$folder")
              docker build -t "$folder_name" "$folder"
            fi
          done
